# Generated by Django 4.1.3 on 2022-11-22 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=1)),
                ("date", models.DateField(max_length=8)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cpf", models.CharField(max_length=11)),
                (
                    "card",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(12),
                            django.core.validators.MinValueValidator(12),
                        ]
                    ),
                ),
                ("hour", models.TimeField()),
                ("shop_owner", models.CharField(max_length=14)),
                ("shop_name", models.CharField(max_length=19)),
            ],
        ),
    ]
