# Generated by Django 4.1.3 on 2022-11-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="card",
            field=models.CharField(max_length=12),
        ),
    ]
