# Generated by Django 4.1.3 on 2022-11-27 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transaction_types", "0004_alter_transactiontype_nature_and_more"),
        ("transactions", "0003_alter_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="transaction_types.transactiontype",
            ),
        ),
    ]
