# Generated by Django 4.1.3 on 2022-11-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransactionType",
            fields=[
                (
                    "type",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=50)),
                (
                    "nature",
                    models.CharField(
                        choices=[("Entrada", "Cash Income"), ("Saída", "Cash Outflow")],
                        default="Entrada",
                        max_length=7,
                    ),
                ),
                (
                    "signal",
                    models.CharField(
                        choices=[("+", "Plus"), ("-", "Minus")],
                        default="+",
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
