# Generated by Django 4.1.3 on 2022-11-30 21:18

from django.db import migrations

DEFAULT_TYPE_VALUES = (
    ("Débito", "Entrada", "+"),
    ("Boleto", "Saída", "-"),
    ("Financiamento", "Saída", "-"),
    ("Crédito", "Entrada", "+"),
    ("Recebimento Empréstimo", "Entrada", "+"),
    ("Vendas", "Entrada", "+"),
    ("Recebimento TED", "Entrada", "+"),
    ("Recebimento DOC", "Entrada", "+"),
    ("Aluguel", "Saída", "-"),
)


def add_transaction_type(apps, schema):
    TransactionType = apps.get_model("transaction_types", "TransactionType")

    for description, nature, signal in DEFAULT_TYPE_VALUES:
        transaction_type = TransactionType(
            description=description, nature=nature, signal=signal
        )
        transaction_type.save()


def remove_transaction_type(apps, schema):
    TransactionType = apps.get_model("transactions", "TransactionType")

    for description, nature, signal in DEFAULT_TYPE_VALUES:
        transaction_type = TransactionType.objects.get(
            description=description, nature=nature, signal=signal
        )
        transaction_type.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("transaction_types", "0001_initial"),
    ]

    operations = [migrations.RunPython(add_transaction_type, remove_transaction_type)]
