# Generated by Django 4.1.3 on 2022-11-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction_types", "0007_alter_transactiontype_nature_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactiontype",
            name="nature",
            field=models.CharField(
                choices=[("Entrada", "Cash Income"), ("Saída", "Cash Outflow")],
                default="Entrada",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="transactiontype",
            name="signal",
            field=models.CharField(
                choices=[("+", "Plus"), ("-", "Minus")], default="+", max_length=1
            ),
        ),
    ]
